default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ab_api_backend_development

test:
  <<: *default
  database: ab_api_backend_test

production:
  <<: *default
  database: ab_api_backend_production
  username: ab_api_backend
  password: <%= ENV['AB_API_BACKEND_DATABASE_PASSWORD'] %>
